### ISSUE TITLE
Use with webpack broken in 0.7.6

### ISSUE THREAD

**Issue by dperetti** [shelljs/shelljs#667]
### Node version (or tell us if you're using electron or some other framework):
Electron

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.6
### Operating system:
OSX
### Description of the bug:

    TypeError: __webpack_require__(...).forEach is not a function
        at eval (webpack:///./~/shelljs/shell.js?:26:25)

### Example ShellJS command to reproduce the error:

```javascript
import { shell } from 'shelljs'
```

Webpack is simply confused by this [commands.json trick](https://github.com/shelljs/shelljs/blob/master/shell.js#L24) introduced in https://github.com/shelljs/shelljs/pull/616.

Works in 0.7.5 before the trick.

**Comment by nfischer** [comment]
@dperetti Thanks for debugging this. Any idea why that doesn't work? I'm not sure why using the JSON would be an issue for webpack only.

**Comment by nfischer** [comment]
Could this perhaps be related to https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/110 or https://github.com/webpack/webpack/issues/1629?

**Comment by dperetti** [comment]
OK It's just that Node automatically turns json files to javascript objects, while Webpack does not.
I can get it to work by adding the json-loader and this to my config.

    { test: /\.json$/, loader: 'json' },

But I don't like much the idea of having to tweak my app config to get a vendor module to work.
Maybe, instead of using `require`, `shell.js` could load and parse the json file directly ?
But from your standpoint, you may not want to have to do this just to get Webpack to work.
And on another hand it's a pity to bite Webpack (rare) users because of one line of code instead of two.
The design decision is up to you !

**Comment by nfischer** [comment]
Thanks for investigating, @dperetti! This is good to know.

Here's an idea. What if we instead change this to `commands.js` (javascript, not JSON), and explicitly export the list with:

```js
exports.list = [
  'cat',
  ...
];
```

This should be mostly the same from our end, and I doubt that could break webpack.

**Comment by nfischer** [comment]
@dperetti can you confirm that #668 works to solve your issue?

**Comment by dperetti** [comment]
Yes, it does. Great !

**Comment by nfischer** [comment]
I'll try to get a patch release out soon for this
