### PR TITLE
fix: switch commands.json -> commands.js

### LINKED ISSUE #667: Use with webpack broken in 0.7.6
### Node version (or tell us if you're using electron or some other framework):
Electron

### ShellJS version (the most recent version/Github branch you see the bug on):
0.7.6
### Operating system:
OSX
### Description of the bug:

    TypeError: __webpack_require__(...).forEach is not a function
        at eval (webpack:///./~/shelljs/shell.js?:26:25)

### Example ShellJS command to reproduce the error:

```javascript
import { shell } from 'shelljs'
```

Webpack is simply confused by this [commands.json trick](https://github.com/shelljs/shelljs/blob/master/shell.js#L24) introduced in https://github.com/shelljs/shelljs/pull/616.

Works in 0.7.5 before the trick.

### PR DESCRIPTION
**Pull request by nfischer**
WebPack has issues with importing JSON directly and using JavaScript
methods on it. For this reason, using the `.forEach()` method on the
imported JSON array caused a method-not-found error.

Instead, we can make this a real JavaScript array by keeping it in a
JavaScript file and exporting it as a field.

Fixes #667

### CODE REVIEW

File: commands.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+exports.list = [
```
Comment (freitagbr) [inline commands.js]: `exports` is initially assigned to `module.exports`. This is why reassigning `exports` doesn't export anything, because `exports` is now whatever you assigned it to, and not `module.exports`.

Anyways, I think it makes more sense to use `module.exports` here, because all we want to export is the array.

File: scripts/generate-docs.js [hunk 2]
```diff
@@ -11,7 +11,7 @@ var docs = grep('^//@', 'shell.js');
 
 // Insert the docs for all the registered commands
 docs = docs.replace(/\/\/@commands\n/g, function () {
-  return require('../commands.json').map(function (commandName) {
+  return require('../commands').list.map(function (commandName) {
```
Comment (freitagbr) [inline scripts/generate-docs.js]: If `module.exports` is used in `commands.js`, this will become `require('../commands').map(...)`.

File: shell.js [hunk 3]
```diff
@@ -21,7 +21,7 @@ var common = require('./src/common');
 //@commands
 
 // Load all default commands
-require('./commands.json').forEach(function (command) {
+require('./commands').list.forEach(function (command) {
```
Comment (freitagbr) [inline shell.js]: Same here.

File: commands.js (hunk 1 above)
Comment (nfischer) [inline commands.js]: Ah, ok. That explanation makes sense. I'll try that instead.

**Comment by nfischer** [comment]
@freitagbr PTAL

**Comment by freitagbr** [comment]
LGTM, CI failures are unrelated.
